server.port=${PORT:8080}
server.address=0.0.0.0

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/studentdb}
spring.datasource.username=${DB_USERNAME:studentuser}
spring.datasource.password=${DB_PASSWORD:root123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.thymeleaf.cache=false